# Generated by Django 4.1.13 on 2024-04-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="password_demo",
            field=models.CharField(max_length=255),
        ),
    ]
