# Generated by Django 4.1.13 on 2024-04-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_password_demo_profile_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
