# Generated by Django 5.0.2 on 2024-03-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
