# Generated by Django 5.0.2 on 2024-02-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0004_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
