# Generated by Django 5.0.2 on 2024-02-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0006_remove_category_level_remove_category_lft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
