# Generated by Django 5.0.2 on 2024-02-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0007_remove_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
