# Generated by Django 5.0.2 on 2024-02-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0008_transaction_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date_save',
        ),
    ]
