# Generated by Django 5.0.2 on 2024-02-28 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0009_remove_transaction_date_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
