# Generated by Django 4.1.13 on 2024-03-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('start_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Начальный баланс')),
                ('icon_folder', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('icon_file', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('icon_folder', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('icon_file', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('transfer', 'Перевод'), ('plus', 'Доход'), ('minus', 'Расход')], db_index=True, default='minus', max_length=20, verbose_name='Тип транзакции')),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('balance', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Баланс')),
                ('date_add', models.DateTimeField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to='andr_finance.account', verbose_name='Счет')),
                ('account_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_recipient', to='andr_finance.account', verbose_name='Счет получатель')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='andr_finance.category', verbose_name='Категория')),
            ],
        ),
    ]
