# Generated by Django 4.1.13 on 2024-03-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('minus', 'Расход'), ('plus', 'Доход'), ('transfer', 'Перевод')], db_index=True, default='minus', max_length=20, verbose_name='Тип транзакции'),
        ),
    ]
