# Generated by Django 5.0.3 on 2024-03-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0002_alter_transaction_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='change',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('minus', 'Расход'), ('plus', 'Доход'), ('transfer', 'Перевод')], default='minus', max_length=20, verbose_name='Тип транзакции'),
        ),
    ]
