# Generated by Django 5.0.3 on 2024-03-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0006_alter_account_icon_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='folder',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Папка иконки'),
        ),
    ]
