# Generated by Django 5.0.3 on 2024-03-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0007_category_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='icon_file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Файл иконки'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_folder',
            field=models.FilePathField(blank=True, default=None, null=True, verbose_name='Папка иконки'),
        ),
    ]
