# Generated by Django 5.0.3 on 2024-03-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0008_remove_category_folder_remove_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, default=None, null=True, verbose_name='Папка иконки'),
        ),
    ]
