# Generated by Django 5.0.3 on 2024-03-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0009_alter_category_icon_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='icon',
        ),
        migrations.AddField(
            model_name='account',
            name='icon_file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Файл иконки'),
        ),
        migrations.AddField(
            model_name='account',
            name='icon_folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, default=None, null=True, verbose_name='Папка иконки'),
        ),
    ]
