# Generated by Django 5.0.3 on 2024-03-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0012_rename_date_added_transaction_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon_file',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='icon_folder',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
