# Generated by Django 5.0.3 on 2024-03-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0013_alter_account_icon_file_alter_account_icon_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_file',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_folder',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
