# Generated by Django 5.0.3 on 2024-03-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andr_finance', '0014_alter_category_icon_file_alter_category_icon_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Баланс'),
        ),
    ]
